language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- python manage.py collectstatic --noinput
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
- coverage run manage.py test
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $ACCESSKEYSECRET
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-590183960597
  on:
    branch: main
env:
  global:
    secure: Bn3Mqi85RpoFsaF/3CwdJDwSdXxY7IuWaDajI9OKtweRk8LdBfUIB5eEOln1mLpHQY7mNmcLWfijKdFGqD5vbRl21A6YuKpqkmGVMkpPyHrhQ0PNuom/BULT1jISslTFS0TrfpUEos4g5tH5gV7Z6it6cDTYSVoVfxlJuoZQ4+MuJvPmn7yDnPZesTadzKZdVkgKNk/MOLemwCBWWhNEUAJWJQhqPabQXOyLMtMnuKWUV7Ub8uHDNeHJPOCQQZa0ilOOtx66bTlAR9UqjMS2Ek4I2ebQ9pRlUku1uZSi11Uh/36Ea6I6bkgYBp/s7rLhxFkJxgmvt2527NBYE4lC3fvm2k/xK5bGnOoxP+TYNRW+8grbCrwfcIZxkItTkfnMMWqEXKMIVJv92+GzqVDmLBOOZ/LfRSyf4iGIEzQo0fZY7oQpFfMbaGGm7wL3ftqmqeCrKsQ5I+gRnbS4+RWXlUs1efYcHF5ivAfCxkwriAHVxHjMUnyJevQqEvIXhsJOLSdbzWQeV0RWFbI5Kh6A/1BE9aYSks6DDF13oAtdqMyJUQgQdPCgJnZbU6NBLE67Hs1GYKtTKFdpnc1LG1Bpt8GmiNe3c7vtUCK6MirjfoG5tyO1OScCTqDqek2aCOU+JIyS/AJs6VkQlrSTgzEIWN5MJobc00GPRoL7YfqK/4k=
dd:
  secure: gpTpmVBywzCRSc5owCT+fmGoy1faeTuabh7yvmV+x/LG4nn/G2fN/W5Rfo0WWIcAYbogv53EhHlXZmAvO4NzUGyqKCJ6iEgU97AcyWozfBLi0JBP/kqK1pKWS+CY8COKGEsWkdslQfzKOYhGdcRf6KoTMsGbqInW6tEoHXtw2i+mNYO6lynoMN+G/kzNcuev0ktZx7cGk5xkMToSREKEqyTD+/oNm876Tw28djYbyjvWHl5XzSPjVgroWcTyLfZGK3k1Kgk679MSGprfCQtbEg7FU8xM4YXhziSjhDx98x2CfG7D/CuvdMFb7JvqG5zADHw/zHOF/DT8j3ssnXNmOKwsltppWGvpzpczkuOFqzHBS6zPtEy1ima8/x2Bpr09aye92MZJlXoQVmhwRuYqEPqUw9AitJxfSFc+Z9UoRDgVuVJMNZNl2RWrMX1HdLffJxXz8Da29vYcMG2ZKoHNyp8oap2RVYqQrqM8Zj1gpmuuMXZYvh7Sy2FIO8m3T9/FOnQhK59KbvgRM4rE2AfAcsOPxbYLOxYdyx/rkYQuGF1w8zhlDE4bICJ95yrRMTzrIlloed1Hr+9kPTFDh3exBKJ0gkfob5dsS4jtNRrE7UE0qIAKL9df++HbAK330M3KZ8m3iRqTmPpsXvv2/ypsZxHIHeNJw2kOJvQDvNQFHIw=
