language: python
python:
- '3.11-dev'
install:
- pip install -r requirements.txt
- python manage.py collectstatic --noinput
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
- coverage run manage.py test
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: ChuTgDiuXOMPJdktutPQ+uh12dRooeOKf87EXTktd1CkAaXoPtMbfOBYEds328z48H55vDZl1yejltraDbFgX4fp0yDopioYxDutgHdBfK2TSEukAS5YihVIDo8DAPKdVNvwCIUIo2rWCpYizD7L/eX71OZqYjsFbU7o/Z4QmI2MIqTpSIGZ4TghMfXRV1jg449RvM7RHXOxL/4MJE2l4jSCJI4uNiSj1XapY+jVeoaBxESl3pJBDobZEiExUb6VEPWSAtO9Lf7r5Jkd8jtNty3f4coZYVbBEClscxhV2uYaofQe85MumDAn1QO3fFslk8A1cgsfgQHp8kHSQQaBJspvV9akdndnAz5g1JDivtJttmHFfdS11noAYq6jiKexcZ1jvz+kimm9bnwCSRjxOsCKlKOPFihIVWLNocoulQG3CynQWyUZt8I3FrGFDe5s1/UyISzc9DNFujR+1fgVMx4GluHm/VvjGNhtmV2jGt442N2jpLjxMnGTm6ssg3eQI1694RArrvsPenpq49J70UZxVKxlhr5exZDlAbZDYHM0Et5fFqRvt87X9hyVY5tiKpPaX3WHNxi4kStYe2GMEbZgotilwWwRVY6u1h9iyHGHl7sTRBg8RGHOcpaA5reJBhwDNVb6hFUG5W1yZ4EUcD3LntfOBx9i7HW03fKmOQQ=
  secret_access_key: 
    secure: adQQPADENLcJp/0wZ3wpl3HMU+CDKMMlEbhgs7Z8UzKz27rkcjt7u666oZhBcQm++vVSFcupm4hDbYquRZ4ymb2N0ZBTffSgkzWlrPgaWGUhAHZJeYloRYKb+COAu97S8mHfR8kpEwjdZa3aS5ubrTgBRvQzWEQeqlf8vXjKtpWCZni+5fSkH8q9WhWe+Zzah7jry6EGa72MuV2Oxttjsc4K5AMenB0M8PfxAcivZAbTQBXlEdpvPkPuyYALl4vPDMDYh6D7JLYqDtUCHxu78N8Fw7KaZvOwV5itvqDyqap2iF+5mfgK43lkViFIo2LFzhG5PESCK8BPOAShoKhOKxXrjdi7KiM7fQfFyF6djKz+mHkbkoPtw/6l5fejd6IDapKjn9iS6+/CAe5rQE4YdSAuZ2kkgKBmX1FoC9IaiiE6/MZJ7Mc4RhiX6S8G4KrZM6fvsNW93de4ksTp8BvZESrZRmSwspNvfNNRUB/3A9W22lXp2WPUPl0gHdILM2C1jEbh0hnad4u27fdRnGWoTlra9ymZnWbyuRgKK0rCryqcDTCEDOvpQLGqDjzqSfxqM59pi5Ub52CtNWLTSSpq67zZssd3cIGDbVPJTrBs7DrdYE0687ab0mYHb0/YnMnSHZmMsVibmpFb4pi8t9Adv3S1d8mgRBAE2kPEMXQN72Q=
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-east-1-508829990173
  on:
    branch: main