language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- python manage.py collectstatic --noinput
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
- coverage run --source=. manage.py test
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "F2hFNu+elH2bhV7dwoYjmx3yuR5DkjVlpY8/Rbvh/EJO02lFj9e7HYxuLb4IEELCtUcz/paY8VDern7hEAniPOPQuQWAw1IraBEfpNL5AGyq6e+Rkl5JfnQ++TTri9gbGWQQZsl7756jbDaElLAYWcxxjSJHIVaLdcFxO+mv1tR1Ncf5X9maAZol4x82Gd6s4/a8mueFDZjJWopOJ3BnAvHKgQ5MNAXbyprMnQKtbZezf9+Dzx61LPYwvH8I9+P+TDp9kE7D9tY4HIOSdazXlOO4KIaNWb/zlZWAAkzETqEI4PlydMCyU99wC1Kw8qtZmr77etuJ8FltFKjP3N6br5pCe7u718r6n77Wl4PskJSLbY0FVWUpDezVzWqdiU6TyRgBMSAi0Fg+Er1ydiTuqbrDT87Hi4i9vPoImjey3ARNqEikEHUDBfPeasOV3UOae4EqEbRG+ubQLYr9p0mJ7y+8bwxkNnkh9Kqlpvkud5VpDWrcGo7/dcy54mnNdDg2monTzJe2Y2jpKp1jKdTCCSQKAaByQiStwrUmE978pXRwdrzlSq4X63vc3rFd+/N43hzaO1mSmG9dirT86uppsV715JdkzshkhHGE3Q6ctmqKotWcFHVZ2TcZGsHX+Kz1rEr927M4adQC7VAjaRNjKiOnrOPB21eytX5SRnT+QRA="
  secret_access_key: 
    secure: "b7+Ai6Eqgh36EaylAXFGsq5B8MUHp8YLPxasoXCVTJsQpReB9HR94vXLgH0d9CqbPSEGB78LotXuTnK3r5yM/iFYs5gE0L9+xtYzh9a5r/zCQhvbI82llvTT35dphqdNuPGg0ab6pSGypcwEWMwOEmDIbl47YCz/UVn9J935vvSltBS6UOane+adh4o09oYbRaREbk1CGcT3ytLWUSy2SQ5C4e7ByFLSNGiw0NYHzNgAeHHCqDR+loUVAp/88v/Cm2m6tyGmJZ98hGpbHNH/yuRtsMpIEJTIAWd2uRgfcxjDavu2CM8D7Dz152ZpjAGzCstG60rI7DfvDqsSza5mUWR4Q2/iKTBT9WfWw5pLnJ0OQKjIbCEguXY9XdpnD9sbb6VZq7DNmi5PQxbfpN4bdtUmllPBygj1fecvvV64F3UawdE7freZBtYz3qHFo0jjCgFKkZOELnC1JaDBzELtR8R7fvNvt8r4gZzbzlpvrkwUEA9tymw7Xla3JhdIDvrS0XvAWa5QMVsAYxU4rVgS1Pk8AVdewy7i5NEma25TVZ5GRROXJotgQNFtNPkSzeodHeSMCMsqAxb8KukHcK5uCM4A+R7eiIqK8BaEBrafyiQvptbo6vQYR1l7fAjHXHSOe0vVWHHc5as/F7YRxSvV6tn/Ckml8S0wp0XRQHWvPV0="  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-590183960597
  skip_cleanup: true
  on:
    branch: main