language: python
matrix:
  include:
  - python: 3.11
install:
- pip install -r requirements.txt
- python manage.py collectstatic --noinput
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
- coverage run --source=. manage.py test
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-590183960597
  on:
    branch: main
  skip_cleanup: 'true'