language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- python manage.py collectstatic --noinput
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
- coverage run manage.py test
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-590183960597
  on:
    branch: main
env:
  global:
    secure: afaxprDnrqOFQvX+/pHrP6I39Ubm2cEfQsKy1WyVtnPCJiR37NZ4EaflgFvyrJ2bzk6W7ohOeq76s14N1otDBWl54BSvEFkqSyjxTpWCpMNlvs95cLS3XJ8fCTW2x8jSPCr7OIua75e42zqtgGbn3LHfce5EH1Km2SqsYBy15DGD6rXCfSsDjOm8duRpe4uVafc6a/lBND2mC1M+dgut4h3Hpl2aDEkbR3nz/8a5oAq201HwWUAYd0ia9P37jcrNFXkPQmJt6PmjV6O3Y/XW1fl8IH8wkD5zGCIuKacs4pt5Z6dNA7+2Is8v1ViT3dlWJ0eVQWL7D9l+6F9IIF/KxHoJEcyhO4dU9HldSm4jFmZFg1W7hKGQ7gt6k4dr7lpQzBXKHFy39+b/hZPhOChxgmc/MdPuhXQ/shNrTr9OJX2rxDG+BAq1hnhJieUjZOaY4Bdqp1H+EMHNZ7JJNoy2jwo0zPIIKolUSNfAuy+NZOgIcC4uXoJjlukEMAsVWHXzNQur62ZpLIHJJhiShTiziUd1OLG9kuNIWy4y0CtLQuqWbNsns9MLcNuM1ideX9xLk4KCSh6RFiobwFh+w2VORLqKvAUXjxrTIVaL0wXVqt0arzUGVuQWODp7feKCqbyw5jMS+6MgKhXKH+CKw5/Z7ZHbjNc58uogp8CXog50Fvw=
dd:
  secure: OAwYJ4rBUq/1XBi5T/uPQk6Ux3AM6du7qQIgKHO4tloYp89I0/vnlXlckA6ggozeSHbRqDQ//P7OBfTRVfec9fbeOoJPtxm5v7ggOUwXejLnc44PDGDgRrw1PGrJoLJQgWWZNhj4P+NW11UUwoK5NUJ9YyZ6Bl5urL2e+i1LD1WjZf2PWtFt5yztxDh+jTRNUIIyQ1A4c3owdjvAqmWxQv0yqiE/HHUOFNgpUou2fUgTc9eZIRvuy4vfRja59chdcE1G0wqGZm3e5kfcehtPrn/AM3W48t1hEZAsuUgVTRt0VA3MxKLFRsDf9v2CHvAgkG7wqN9rvUh9H47oewC2syS19T/Y42byGwxW4/FfvskG8GD6OAtGVOWlyqWXSypk3gUSOt0+lROURV6ySdC9rLTbgdmioF09v0xhaiGJSKBG6FiYTFhi4/mln4YfYSJfys8IjjBpiGznMzKc/f7ARKDDUhWhbGf4ZfcxBoX0m2CJkhJfBdjePkimb8YiANpDb8KclDz/WrH1sPQ9Uj1cTana2/qfRFvdMghQVb9HwbFk4tApxWiP4RTQdMfCCj9YEX0RDaolWDWkSqVT4Ppf3GAHSUCwlGnT74DFpk2KZMstTeC7TgYC50zS1eOQHXt3xHXQMGPlpqIo94bue0Eaoroi9z0i7iOwEoQ1l4h20G4=
